# Generated by Django 3.2.6 on 2021-08-13 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to=settings.AUTH_USER_MODEL),
        ),
    ]
