# Generated by Django 3.2.6 on 2021-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_work_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
