# Generated by Django 3.2.6 on 2021-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_work_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files'),
        ),
    ]
