# Generated by Django 3.2.6 on 2021-08-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210811_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='to_do',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
