# Generated by Django 3.2.6 on 2021-08-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210811_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do',
            options={'ordering': ['is_complete', 'due_date']},
        ),
    ]
