# Generated by Django 3.2.6 on 2021-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='background',
            field=models.ImageField(blank=True, default='defaults/profile_background/default.jpg', upload_to='upload/profile_background'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/profile_pictures/default.png', upload_to='upload/profile_pictures'),
        ),
    ]
