# Generated by Django 3.2.6 on 2021-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210814_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='background',
            field=models.ImageField(blank=True, default='uploads/profile_background/default.jpg', upload_to='uploads/profile_background'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
